### ISSUE TITLE
--get-rivers issue

### ISSUE THREAD

**Issue by ctenvelden** [openearth/hydro-engine#20]
--get-rivers werkt niet voor Krishna basin in India --> het niet opgeven van een river shp geeft error.

settings.json:

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.89190,
          15.98302
        ]
      }
    }
  ]
}

(Extra info: het in de modelbuilder handmatig opgeven van river shp van Natural Earth Data geeft vreemde ldd, handmatig opgeven van Hydrosheds river shp geeft goede ldd.)

**Comment by gena** [comment]
... this is quite large reservoir :), testing ...

![image](https://user-images.githubusercontent.com/169821/40848653-18b0c85e-65c0-11e8-9eb9-755e0e765943.png)

**Comment by gena** [comment]
Seems to work, here are two exports:

All branches (thin lines):
`hydroengine region.json --get-rivers rivers_all.json --filter-upstream-gt 0`

Branches with threshold > 1000 (thick lines)
`hydroengine region.json --get-rivers rivers_all.json --filter-upstream-gt 1000`

![image](https://user-images.githubusercontent.com/169821/40947594-c860e61c-6863-11e8-8033-f58d99509d19.png)
