### ISSUE TITLE
EEException: Earth Engine memory capacity exceeded

### ISSUE THREAD

**Issue by martham93** [openearth/hydro-engine#35]
* hydro-engine version: 0.0.30
* Python version: 3.6.6
* Operating System: OS

### Description
I'm trying to download many ~100,000 AOIs using the `hydroengine.get_catchment()` function, but after ~10,000 AOIs, the script fails with the error `EEException: Earth Engine memory capacity exceeded`, I've made sure to include a sleep in the code so to not exceed the GEE rate limit, and I feel confident that my AOIs are not too big. 

### What I Did

```
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://hydro-engine.appspot.com/get_catchments
```

Do you have any suggestions for how to avoid the `EEException: Earth Engine memory capacity exceeded` error? Thanks for your time.

**Comment by gena** [comment]
Most probably this has to do with the size of the asset. Currently, this is limited to ~1GB (the limit of EE for getDownloadURL() function). I only wonder if it's EE that limits that or if something else happening. Did you try to repeat request only for that last failing catchment after some longer delay?

The solution could be to reduce the region size and querying data per smaller sub-catchment, but you've indicated that it is already not too large. 

It could be that EE enforces some quota limits per service account as well, we may need to check with EE team to see if that is the case.

**Comment by martham93** [comment]
Hello thanks for your response. 

So this is an example tile: 
```
{'type': 'Polygon',
 'coordinates': (((-101.6015625, 32.6953125),
   (-101.6015625, 33.046875),
   (-101.953125, 33.046875),
   (-101.953125, 32.6953125),
   (-101.6015625, 32.6953125)),)}
```

I just repeated the request for just the single failing catchment (geometry included above) and it ran without any issue. 

I think you're right that  there is an EE quota going on...  Do you know how I should contact them to get more information about that?

**Comment by gena** [comment]
@tylere, do you maybe know what kind of quota is there used for service accounts here?

**Comment by gena** [comment]
@martham93, for this kind of global exports it might be easier to turn directly to Earth Engine and export these datasets for the whole world, and then just clip them with the regions you're interested in locally. I can share a script to access the underlying datasets if that is an option.

**Comment by martham93** [comment]
okay that would be great thank you so much! I would love to see the script you use with EE directly

**Comment by gena** [comment]
The following script basically emulates get-raster: https://code.earthengine.google.com/ac907d9fad3793ba58e829049b2febf7, you can probably export what is needed using [Export.image.toDrive()](https://developers.google.com/earth-engine/tutorial_api_07#exporting-images) or to Cloud Storage.

**Comment by martham93** [comment]
thank you so much I'll work with that script.

**Comment by tylere** [comment]
Service accounts have the same quota restrictions as standard user accounts.
For exports of this size, you will be better off using a batch Export, as @gena suggested.
